/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityEventType = { 'action' : null } |
  { 'login' : null } |
  { 'permissionChange' : null };
export interface AlertView {
  'id' : Id,
  'resolved' : boolean,
  'value' : bigint,
  'threshold' : bigint,
  'productId' : bigint,
  'timestamp' : Timestamp,
  'severity' : MetricSeverity,
  'metricType' : string,
  'resolvedAt' : [] | [Timestamp],
}
export type EmailConfigId = bigint;
export interface EmailConfigView {
  'id' : EmailConfigId,
  'bounceEmail' : string,
  'createdAt' : Timestamp,
  'productId' : bigint,
  'isActive' : boolean,
  'senderName' : string,
  'senderEmail' : string,
}
export interface EmailLog {
  'id' : Id,
  'status' : EmailStatus,
  'subject' : string,
  'recipient' : string,
  'productId' : bigint,
  'timestamp' : Timestamp,
}
export type EmailStatus = { 'sent' : null } |
  { 'failed' : null } |
  { 'bounced' : null };
export interface EmailTemplateView {
  'id' : Id,
  'subject' : string,
  'body' : string,
  'name' : string,
  'productId' : bigint,
  'lastModified' : Timestamp,
}
export type Id = bigint;
export interface IssueComment {
  'id' : Id,
  'content' : string,
  'authorId' : bigint,
  'issueId' : IssueId,
  'timestamp' : Timestamp,
}
export type IssueId = bigint;
export type IssueSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export type IssueStatus = { 'resolved' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export interface IssueView {
  'id' : IssueId,
  'status' : IssueStatus,
  'title' : string,
  'assignedTo' : [] | [bigint],
  'createdAt' : Timestamp,
  'description' : string,
  'productId' : bigint,
  'updatedAt' : Timestamp,
  'severity' : IssueSeverity,
}
export type LinkedAppId = string;
export interface LinkedAppView {
  'id' : LinkedAppId,
  'status' : string,
  'baseUrl' : string,
  'appCode' : string,
  'name' : string,
  'addedAt' : Timestamp,
}
export type MetricSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export type NotificationSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null };
export type NotificationType = { 'systemAlert' : null } |
  { 'user' : null } |
  { 'update' : null } |
  { 'issue' : null };
export interface NotificationView {
  'id' : Id,
  'title' : string,
  'notifType' : NotificationType,
  'body' : string,
  'createdAt' : Timestamp,
  'productId' : [] | [bigint],
  'isRead' : boolean,
  'snoozedUntil' : [] | [Timestamp],
  'severity' : NotificationSeverity,
  'snoozed' : boolean,
}
export type ProductId = bigint;
export type ProductStatus = { 'disconnected' : null } |
  { 'connected' : null };
export interface ProductView {
  'id' : ProductId,
  'status' : ProductStatus,
  'code' : string,
  'name' : string,
  'description' : string,
  'registeredAt' : Timestamp,
  'lastSync' : Timestamp,
}
export interface SystemMetrics {
  'id' : Id,
  'cpu' : bigint,
  'memory' : bigint,
  'disk' : bigint,
  'productId' : bigint,
  'connectionStatus' : string,
  'timestamp' : Timestamp,
  'networkUptime' : bigint,
  'apiLatency' : bigint,
}
export type Time = bigint;
export type Timestamp = bigint;
export type UpdateId = bigint;
export type UpdateStatus = { 'deployed' : null } |
  { 'scheduled' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface UpdateView {
  'id' : UpdateId,
  'status' : UpdateStatus,
  'deployedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'size' : bigint,
  'productId' : bigint,
  'releaseNotes' : string,
  'version' : string,
  'scheduledAt' : [] | [Timestamp],
}
export interface UserActivity {
  'id' : Id,
  'userId' : UserId,
  'description' : string,
  'productId' : bigint,
  'timestamp' : Timestamp,
  'eventType' : ActivityEventType,
}
export type UserId = bigint;
export type UserRole = { 'manager' : null } |
  { 'admin' : null } |
  { 'viewer' : null };
export type UserStatus = { 'active' : null } |
  { 'suspended' : null };
export interface UserView {
  'id' : UserId,
  'status' : UserStatus,
  'lastActivity' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'productId' : bigint,
  'email' : string,
}
export interface _SERVICE {
  'addEmailLog' : ActorMethod<[bigint, string, string, EmailStatus], EmailLog>,
  'addIssueComment' : ActorMethod<[bigint, string, bigint], IssueComment>,
  'createAlert' : ActorMethod<
    [bigint, string, MetricSeverity, bigint, bigint],
    AlertView
  >,
  'createEmailConfig' : ActorMethod<
    [bigint, string, string, string],
    EmailConfigView
  >,
  'createEmailTemplate' : ActorMethod<
    [bigint, string, string, string],
    EmailTemplateView
  >,
  'createIssue' : ActorMethod<
    [string, string, IssueSeverity, bigint, [] | [bigint]],
    IssueView
  >,
  'createNotification' : ActorMethod<
    [string, string, NotificationSeverity, NotificationType, [] | [bigint]],
    NotificationView
  >,
  'createUpdate' : ActorMethod<[bigint, string, string, bigint], UpdateView>,
  'createUser' : ActorMethod<[bigint, string, string, UserRole], UserView>,
  'deleteEmailConfig' : ActorMethod<[bigint], undefined>,
  'deleteEmailTemplate' : ActorMethod<[bigint], undefined>,
  'disconnectProduct' : ActorMethod<[bigint], undefined>,
  'dismissNotification' : ActorMethod<[bigint], undefined>,
  'getLatestMetrics' : ActorMethod<[bigint], [] | [SystemMetrics]>,
  'getMetricsHistory' : ActorMethod<[bigint], Array<SystemMetrics>>,
  'getProduct' : ActorMethod<[bigint], [] | [ProductView]>,
  'listActiveAlerts' : ActorMethod<[], Array<AlertView>>,
  'listAlertHistory' : ActorMethod<[bigint], Array<AlertView>>,
  'listAllUpdates' : ActorMethod<[], Array<UpdateView>>,
  'listEmailConfigs' : ActorMethod<[bigint], Array<EmailConfigView>>,
  'listEmailLogs' : ActorMethod<[bigint], Array<EmailLog>>,
  'listEmailTemplates' : ActorMethod<[bigint], Array<EmailTemplateView>>,
  'listIssueComments' : ActorMethod<[bigint], Array<IssueComment>>,
  'listIssues' : ActorMethod<
    [[] | [bigint], [] | [IssueStatus], [] | [IssueSeverity]],
    Array<IssueView>
  >,
  'listLinkedApps' : ActorMethod<[], Array<LinkedAppView>>,
  'listNotifications' : ActorMethod<
    [[] | [NotificationType], [] | [bigint], [] | [boolean]],
    Array<NotificationView>
  >,
  'listProductUpdates' : ActorMethod<[bigint], Array<UpdateView>>,
  'listProducts' : ActorMethod<[], Array<ProductView>>,
  'listUserActivities' : ActorMethod<[bigint], Array<UserActivity>>,
  'listUsers' : ActorMethod<[], Array<UserView>>,
  'listUsersByProduct' : ActorMethod<[bigint], Array<UserView>>,
  'logUserActivity' : ActorMethod<
    [bigint, bigint, ActivityEventType, string],
    undefined
  >,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'markUpdateDeployed' : ActorMethod<[bigint], undefined>,
  'reconnectProduct' : ActorMethod<[bigint], undefined>,
  'registerLinkedApp' : ActorMethod<[string, string, string], LinkedAppView>,
  'registerProduct' : ActorMethod<[string, string, string], ProductView>,
  'removeLinkedApp' : ActorMethod<[string], boolean>,
  'removeUser' : ActorMethod<[bigint], undefined>,
  'resolveAlert' : ActorMethod<[bigint], undefined>,
  'resolveIssue' : ActorMethod<[bigint], undefined>,
  'restoreUser' : ActorMethod<[bigint], undefined>,
  'scheduleUpdate' : ActorMethod<[bigint, Time], undefined>,
  'snoozeNotification' : ActorMethod<[bigint, Time], undefined>,
  'submitMetrics' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, string],
    SystemMetrics
  >,
  'suspendUser' : ActorMethod<[bigint], undefined>,
  'syncProduct' : ActorMethod<[bigint], undefined>,
  'updateEmailConfig' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateEmailTemplate' : ActorMethod<[bigint, string, string], undefined>,
  'updateIssue' : ActorMethod<
    [bigint, string, string, IssueSeverity, IssueStatus, [] | [bigint]],
    undefined
  >,
  'updateLinkedAppStatus' : ActorMethod<[string, string], [] | [LinkedAppView]>,
  'updateProductMeta' : ActorMethod<[bigint, string, string], undefined>,
  'updateUserRole' : ActorMethod<[bigint, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];