/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmailStatus = IDL.Variant({
  'sent' : IDL.Null,
  'failed' : IDL.Null,
  'bounced' : IDL.Null,
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const EmailLog = IDL.Record({
  'id' : Id,
  'status' : EmailStatus,
  'subject' : IDL.Text,
  'recipient' : IDL.Text,
  'productId' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const IssueId = IDL.Nat;
export const IssueComment = IDL.Record({
  'id' : Id,
  'content' : IDL.Text,
  'authorId' : IDL.Nat,
  'issueId' : IssueId,
  'timestamp' : Timestamp,
});
export const MetricSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const AlertView = IDL.Record({
  'id' : Id,
  'resolved' : IDL.Bool,
  'value' : IDL.Nat,
  'threshold' : IDL.Nat,
  'productId' : IDL.Nat,
  'timestamp' : Timestamp,
  'severity' : MetricSeverity,
  'metricType' : IDL.Text,
  'resolvedAt' : IDL.Opt(Timestamp),
});
export const EmailConfigId = IDL.Nat;
export const EmailConfigView = IDL.Record({
  'id' : EmailConfigId,
  'bounceEmail' : IDL.Text,
  'createdAt' : Timestamp,
  'productId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const EmailTemplateView = IDL.Record({
  'id' : Id,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'lastModified' : Timestamp,
});
export const IssueSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const IssueStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const IssueView = IDL.Record({
  'id' : IssueId,
  'status' : IssueStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'updatedAt' : Timestamp,
  'severity' : IssueSeverity,
});
export const NotificationSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'critical' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'systemAlert' : IDL.Null,
  'user' : IDL.Null,
  'update' : IDL.Null,
  'issue' : IDL.Null,
});
export const NotificationView = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'productId' : IDL.Opt(IDL.Nat),
  'isRead' : IDL.Bool,
  'snoozedUntil' : IDL.Opt(Timestamp),
  'severity' : NotificationSeverity,
  'snoozed' : IDL.Bool,
});
export const UpdateId = IDL.Nat;
export const UpdateStatus = IDL.Variant({
  'deployed' : IDL.Null,
  'scheduled' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
});
export const UpdateView = IDL.Record({
  'id' : UpdateId,
  'status' : UpdateStatus,
  'deployedAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'size' : IDL.Nat,
  'productId' : IDL.Nat,
  'releaseNotes' : IDL.Text,
  'version' : IDL.Text,
  'scheduledAt' : IDL.Opt(Timestamp),
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'viewer' : IDL.Null,
});
export const UserId = IDL.Nat;
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const UserView = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'lastActivity' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'productId' : IDL.Nat,
  'email' : IDL.Text,
});
export const SystemMetrics = IDL.Record({
  'id' : Id,
  'cpu' : IDL.Nat,
  'memory' : IDL.Nat,
  'disk' : IDL.Nat,
  'productId' : IDL.Nat,
  'connectionStatus' : IDL.Text,
  'timestamp' : Timestamp,
  'networkUptime' : IDL.Nat,
  'apiLatency' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const ProductStatus = IDL.Variant({
  'disconnected' : IDL.Null,
  'connected' : IDL.Null,
});
export const ProductView = IDL.Record({
  'id' : ProductId,
  'status' : ProductStatus,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'registeredAt' : Timestamp,
  'lastSync' : Timestamp,
});
export const LinkedAppId = IDL.Text;
export const LinkedAppView = IDL.Record({
  'id' : LinkedAppId,
  'status' : IDL.Text,
  'baseUrl' : IDL.Text,
  'appCode' : IDL.Text,
  'name' : IDL.Text,
  'addedAt' : Timestamp,
});
export const ActivityEventType = IDL.Variant({
  'action' : IDL.Null,
  'login' : IDL.Null,
  'permissionChange' : IDL.Null,
});
export const UserActivity = IDL.Record({
  'id' : Id,
  'userId' : UserId,
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'timestamp' : Timestamp,
  'eventType' : ActivityEventType,
});
export const Time = IDL.Int;

export const idlService = IDL.Service({
  'addEmailLog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, EmailStatus],
      [EmailLog],
      [],
    ),
  'addIssueComment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IssueComment],
      [],
    ),
  'createAlert' : IDL.Func(
      [IDL.Nat, IDL.Text, MetricSeverity, IDL.Nat, IDL.Nat],
      [AlertView],
      [],
    ),
  'createEmailConfig' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [EmailConfigView],
      [],
    ),
  'createEmailTemplate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [EmailTemplateView],
      [],
    ),
  'createIssue' : IDL.Func(
      [IDL.Text, IDL.Text, IssueSeverity, IDL.Nat, IDL.Opt(IDL.Nat)],
      [IssueView],
      [],
    ),
  'createNotification' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        NotificationSeverity,
        NotificationType,
        IDL.Opt(IDL.Nat),
      ],
      [NotificationView],
      [],
    ),
  'createUpdate' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [UpdateView],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, UserRole],
      [UserView],
      [],
    ),
  'deleteEmailConfig' : IDL.Func([IDL.Nat], [], []),
  'deleteEmailTemplate' : IDL.Func([IDL.Nat], [], []),
  'disconnectProduct' : IDL.Func([IDL.Nat], [], []),
  'dismissNotification' : IDL.Func([IDL.Nat], [], []),
  'getLatestMetrics' : IDL.Func([IDL.Nat], [IDL.Opt(SystemMetrics)], ['query']),
  'getMetricsHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SystemMetrics)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductView)], ['query']),
  'listActiveAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
  'listAlertHistory' : IDL.Func([IDL.Nat], [IDL.Vec(AlertView)], ['query']),
  'listAllUpdates' : IDL.Func([], [IDL.Vec(UpdateView)], ['query']),
  'listEmailConfigs' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EmailConfigView)],
      ['query'],
    ),
  'listEmailLogs' : IDL.Func([IDL.Nat], [IDL.Vec(EmailLog)], ['query']),
  'listEmailTemplates' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EmailTemplateView)],
      ['query'],
    ),
  'listIssueComments' : IDL.Func([IDL.Nat], [IDL.Vec(IssueComment)], ['query']),
  'listIssues' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IssueStatus), IDL.Opt(IssueSeverity)],
      [IDL.Vec(IssueView)],
      ['query'],
    ),
  'listLinkedApps' : IDL.Func([], [IDL.Vec(LinkedAppView)], ['query']),
  'listNotifications' : IDL.Func(
      [IDL.Opt(NotificationType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
      [IDL.Vec(NotificationView)],
      ['query'],
    ),
  'listProductUpdates' : IDL.Func([IDL.Nat], [IDL.Vec(UpdateView)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'listUserActivities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserActivity)],
      ['query'],
    ),
  'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
  'listUsersByProduct' : IDL.Func([IDL.Nat], [IDL.Vec(UserView)], ['query']),
  'logUserActivity' : IDL.Func(
      [IDL.Nat, IDL.Nat, ActivityEventType, IDL.Text],
      [],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'markUpdateDeployed' : IDL.Func([IDL.Nat], [], []),
  'reconnectProduct' : IDL.Func([IDL.Nat], [], []),
  'registerLinkedApp' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [LinkedAppView],
      [],
    ),
  'registerProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ProductView],
      [],
    ),
  'removeLinkedApp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeUser' : IDL.Func([IDL.Nat], [], []),
  'resolveAlert' : IDL.Func([IDL.Nat], [], []),
  'resolveIssue' : IDL.Func([IDL.Nat], [], []),
  'restoreUser' : IDL.Func([IDL.Nat], [], []),
  'scheduleUpdate' : IDL.Func([IDL.Nat, Time], [], []),
  'snoozeNotification' : IDL.Func([IDL.Nat, Time], [], []),
  'submitMetrics' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [SystemMetrics],
      [],
    ),
  'suspendUser' : IDL.Func([IDL.Nat], [], []),
  'syncProduct' : IDL.Func([IDL.Nat], [], []),
  'updateEmailConfig' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateEmailTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateIssue' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IssueSeverity,
        IssueStatus,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateLinkedAppStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(LinkedAppView)],
      [],
    ),
  'updateProductMeta' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmailStatus = IDL.Variant({
    'sent' : IDL.Null,
    'failed' : IDL.Null,
    'bounced' : IDL.Null,
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const EmailLog = IDL.Record({
    'id' : Id,
    'status' : EmailStatus,
    'subject' : IDL.Text,
    'recipient' : IDL.Text,
    'productId' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const IssueId = IDL.Nat;
  const IssueComment = IDL.Record({
    'id' : Id,
    'content' : IDL.Text,
    'authorId' : IDL.Nat,
    'issueId' : IssueId,
    'timestamp' : Timestamp,
  });
  const MetricSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const AlertView = IDL.Record({
    'id' : Id,
    'resolved' : IDL.Bool,
    'value' : IDL.Nat,
    'threshold' : IDL.Nat,
    'productId' : IDL.Nat,
    'timestamp' : Timestamp,
    'severity' : MetricSeverity,
    'metricType' : IDL.Text,
    'resolvedAt' : IDL.Opt(Timestamp),
  });
  const EmailConfigId = IDL.Nat;
  const EmailConfigView = IDL.Record({
    'id' : EmailConfigId,
    'bounceEmail' : IDL.Text,
    'createdAt' : Timestamp,
    'productId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const EmailTemplateView = IDL.Record({
    'id' : Id,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'lastModified' : Timestamp,
  });
  const IssueSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const IssueStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const IssueView = IDL.Record({
    'id' : IssueId,
    'status' : IssueStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'updatedAt' : Timestamp,
    'severity' : IssueSeverity,
  });
  const NotificationSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'systemAlert' : IDL.Null,
    'user' : IDL.Null,
    'update' : IDL.Null,
    'issue' : IDL.Null,
  });
  const NotificationView = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'productId' : IDL.Opt(IDL.Nat),
    'isRead' : IDL.Bool,
    'snoozedUntil' : IDL.Opt(Timestamp),
    'severity' : NotificationSeverity,
    'snoozed' : IDL.Bool,
  });
  const UpdateId = IDL.Nat;
  const UpdateStatus = IDL.Variant({
    'deployed' : IDL.Null,
    'scheduled' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const UpdateView = IDL.Record({
    'id' : UpdateId,
    'status' : UpdateStatus,
    'deployedAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'size' : IDL.Nat,
    'productId' : IDL.Nat,
    'releaseNotes' : IDL.Text,
    'version' : IDL.Text,
    'scheduledAt' : IDL.Opt(Timestamp),
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'viewer' : IDL.Null,
  });
  const UserId = IDL.Nat;
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const UserView = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'lastActivity' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'productId' : IDL.Nat,
    'email' : IDL.Text,
  });
  const SystemMetrics = IDL.Record({
    'id' : Id,
    'cpu' : IDL.Nat,
    'memory' : IDL.Nat,
    'disk' : IDL.Nat,
    'productId' : IDL.Nat,
    'connectionStatus' : IDL.Text,
    'timestamp' : Timestamp,
    'networkUptime' : IDL.Nat,
    'apiLatency' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const ProductStatus = IDL.Variant({
    'disconnected' : IDL.Null,
    'connected' : IDL.Null,
  });
  const ProductView = IDL.Record({
    'id' : ProductId,
    'status' : ProductStatus,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'registeredAt' : Timestamp,
    'lastSync' : Timestamp,
  });
  const LinkedAppId = IDL.Text;
  const LinkedAppView = IDL.Record({
    'id' : LinkedAppId,
    'status' : IDL.Text,
    'baseUrl' : IDL.Text,
    'appCode' : IDL.Text,
    'name' : IDL.Text,
    'addedAt' : Timestamp,
  });
  const ActivityEventType = IDL.Variant({
    'action' : IDL.Null,
    'login' : IDL.Null,
    'permissionChange' : IDL.Null,
  });
  const UserActivity = IDL.Record({
    'id' : Id,
    'userId' : UserId,
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'timestamp' : Timestamp,
    'eventType' : ActivityEventType,
  });
  const Time = IDL.Int;
  
  return IDL.Service({
    'addEmailLog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, EmailStatus],
        [EmailLog],
        [],
      ),
    'addIssueComment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IssueComment],
        [],
      ),
    'createAlert' : IDL.Func(
        [IDL.Nat, IDL.Text, MetricSeverity, IDL.Nat, IDL.Nat],
        [AlertView],
        [],
      ),
    'createEmailConfig' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [EmailConfigView],
        [],
      ),
    'createEmailTemplate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [EmailTemplateView],
        [],
      ),
    'createIssue' : IDL.Func(
        [IDL.Text, IDL.Text, IssueSeverity, IDL.Nat, IDL.Opt(IDL.Nat)],
        [IssueView],
        [],
      ),
    'createNotification' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          NotificationSeverity,
          NotificationType,
          IDL.Opt(IDL.Nat),
        ],
        [NotificationView],
        [],
      ),
    'createUpdate' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [UpdateView],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, UserRole],
        [UserView],
        [],
      ),
    'deleteEmailConfig' : IDL.Func([IDL.Nat], [], []),
    'deleteEmailTemplate' : IDL.Func([IDL.Nat], [], []),
    'disconnectProduct' : IDL.Func([IDL.Nat], [], []),
    'dismissNotification' : IDL.Func([IDL.Nat], [], []),
    'getLatestMetrics' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SystemMetrics)],
        ['query'],
      ),
    'getMetricsHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SystemMetrics)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(ProductView)], ['query']),
    'listActiveAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
    'listAlertHistory' : IDL.Func([IDL.Nat], [IDL.Vec(AlertView)], ['query']),
    'listAllUpdates' : IDL.Func([], [IDL.Vec(UpdateView)], ['query']),
    'listEmailConfigs' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EmailConfigView)],
        ['query'],
      ),
    'listEmailLogs' : IDL.Func([IDL.Nat], [IDL.Vec(EmailLog)], ['query']),
    'listEmailTemplates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EmailTemplateView)],
        ['query'],
      ),
    'listIssueComments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IssueComment)],
        ['query'],
      ),
    'listIssues' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IssueStatus), IDL.Opt(IssueSeverity)],
        [IDL.Vec(IssueView)],
        ['query'],
      ),
    'listLinkedApps' : IDL.Func([], [IDL.Vec(LinkedAppView)], ['query']),
    'listNotifications' : IDL.Func(
        [IDL.Opt(NotificationType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Bool)],
        [IDL.Vec(NotificationView)],
        ['query'],
      ),
    'listProductUpdates' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UpdateView)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'listUserActivities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserActivity)],
        ['query'],
      ),
    'listUsers' : IDL.Func([], [IDL.Vec(UserView)], ['query']),
    'listUsersByProduct' : IDL.Func([IDL.Nat], [IDL.Vec(UserView)], ['query']),
    'logUserActivity' : IDL.Func(
        [IDL.Nat, IDL.Nat, ActivityEventType, IDL.Text],
        [],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'markUpdateDeployed' : IDL.Func([IDL.Nat], [], []),
    'reconnectProduct' : IDL.Func([IDL.Nat], [], []),
    'registerLinkedApp' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [LinkedAppView],
        [],
      ),
    'registerProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ProductView],
        [],
      ),
    'removeLinkedApp' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeUser' : IDL.Func([IDL.Nat], [], []),
    'resolveAlert' : IDL.Func([IDL.Nat], [], []),
    'resolveIssue' : IDL.Func([IDL.Nat], [], []),
    'restoreUser' : IDL.Func([IDL.Nat], [], []),
    'scheduleUpdate' : IDL.Func([IDL.Nat, Time], [], []),
    'snoozeNotification' : IDL.Func([IDL.Nat, Time], [], []),
    'submitMetrics' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [SystemMetrics],
        [],
      ),
    'suspendUser' : IDL.Func([IDL.Nat], [], []),
    'syncProduct' : IDL.Func([IDL.Nat], [], []),
    'updateEmailConfig' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateEmailTemplate' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateIssue' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IssueSeverity,
          IssueStatus,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateLinkedAppStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(LinkedAppView)],
        [],
      ),
    'updateProductMeta' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateUserRole' : IDL.Func([IDL.Nat, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };