/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AlertView {
    id: Id;
    resolved: boolean;
    value: bigint;
    threshold: bigint;
    productId: bigint;
    timestamp: Timestamp;
    severity: MetricSeverity;
    metricType: string;
    resolvedAt?: Timestamp;
}
export type Timestamp = bigint;
export type Time = bigint;
export interface IssueComment {
    id: Id;
    content: string;
    authorId: bigint;
    issueId: IssueId;
    timestamp: Timestamp;
}
export interface UserView {
    id: UserId;
    status: UserStatus;
    lastActivity: Timestamp;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    productId: bigint;
    email: string;
}
export interface EmailLog {
    id: Id;
    status: EmailStatus;
    subject: string;
    recipient: string;
    productId: bigint;
    timestamp: Timestamp;
}
export type EmailConfigId = bigint;
export type UpdateId = bigint;
export interface NotificationView {
    id: Id;
    title: string;
    notifType: NotificationType;
    body: string;
    createdAt: Timestamp;
    productId?: bigint;
    isRead: boolean;
    snoozedUntil?: Timestamp;
    severity: NotificationSeverity;
    snoozed: boolean;
}
export interface LinkedAppView {
    id: LinkedAppId;
    status: string;
    baseUrl: string;
    appCode: string;
    name: string;
    addedAt: Timestamp;
}
export interface EmailTemplateView {
    id: Id;
    subject: string;
    body: string;
    name: string;
    productId: bigint;
    lastModified: Timestamp;
}
export interface IssueView {
    id: IssueId;
    status: IssueStatus;
    title: string;
    assignedTo?: bigint;
    createdAt: Timestamp;
    description: string;
    productId: bigint;
    updatedAt: Timestamp;
    severity: IssueSeverity;
}
export type IssueId = bigint;
export interface EmailConfigView {
    id: EmailConfigId;
    bounceEmail: string;
    createdAt: Timestamp;
    productId: bigint;
    isActive: boolean;
    senderName: string;
    senderEmail: string;
}
export interface SystemMetrics {
    id: Id;
    cpu: bigint;
    memory: bigint;
    disk: bigint;
    productId: bigint;
    connectionStatus: string;
    timestamp: Timestamp;
    networkUptime: bigint;
    apiLatency: bigint;
}
export type LinkedAppId = string;
export type UserId = bigint;
export interface ProductView {
    id: ProductId;
    status: ProductStatus;
    code: string;
    name: string;
    description: string;
    registeredAt: Timestamp;
    lastSync: Timestamp;
}
export type Id = bigint;
export type ProductId = bigint;
export interface UserActivity {
    id: Id;
    userId: UserId;
    description: string;
    productId: bigint;
    timestamp: Timestamp;
    eventType: ActivityEventType;
}
export interface UpdateView {
    id: UpdateId;
    status: UpdateStatus;
    deployedAt?: Timestamp;
    createdAt: Timestamp;
    size: bigint;
    productId: bigint;
    releaseNotes: string;
    version: string;
    scheduledAt?: Timestamp;
}
export enum ActivityEventType {
    action = "action",
    login = "login",
    permissionChange = "permissionChange"
}
export enum EmailStatus {
    sent = "sent",
    failed = "failed",
    bounced = "bounced"
}
export enum IssueSeverity {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum IssueStatus {
    resolved = "resolved",
    in_progress = "in_progress",
    open = "open"
}
export enum NotificationSeverity {
    warning = "warning",
    info = "info",
    critical = "critical"
}
export enum NotificationType {
    systemAlert = "systemAlert",
    user = "user",
    update = "update",
    issue = "issue"
}
export enum ProductStatus {
    disconnected = "disconnected",
    connected = "connected"
}
export enum UpdateStatus {
    deployed = "deployed",
    scheduled = "scheduled",
    pending = "pending",
    failed = "failed"
}
export enum UserRole {
    manager = "manager",
    admin = "admin",
    viewer = "viewer"
}
export enum UserStatus {
    active = "active",
    suspended = "suspended"
}
export interface backendInterface {
    addEmailLog(productId: bigint, recipient: string, subject: string, status: EmailStatus): Promise<EmailLog>;
    addIssueComment(issueId: bigint, content: string, authorId: bigint): Promise<IssueComment>;
    createAlert(productId: bigint, metricType: string, severity: MetricSeverity, value: bigint, threshold: bigint): Promise<AlertView>;
    createEmailConfig(productId: bigint, senderName: string, senderEmail: string, bounceEmail: string): Promise<EmailConfigView>;
    createEmailTemplate(productId: bigint, name: string, subject: string, body: string): Promise<EmailTemplateView>;
    createIssue(title: string, description: string, severity: IssueSeverity, productId: bigint, assignedTo: bigint | null): Promise<IssueView>;
    createNotification(title: string, body: string, severity: NotificationSeverity, notifType: NotificationType, productId: bigint | null): Promise<NotificationView>;
    createUpdate(productId: bigint, version: string, releaseNotes: string, size: bigint): Promise<UpdateView>;
    createUser(productId: bigint, name: string, email: string, role: UserRole): Promise<UserView>;
    deleteEmailConfig(id: bigint): Promise<void>;
    deleteEmailTemplate(id: bigint): Promise<void>;
    disconnectProduct(id: bigint): Promise<void>;
    dismissNotification(id: bigint): Promise<void>;
    getLatestMetrics(productId: bigint): Promise<SystemMetrics | null>;
    getMetricsHistory(productId: bigint): Promise<Array<SystemMetrics>>;
    getProduct(id: bigint): Promise<ProductView | null>;
    listActiveAlerts(): Promise<Array<AlertView>>;
    listAlertHistory(productId: bigint): Promise<Array<AlertView>>;
    listAllUpdates(): Promise<Array<UpdateView>>;
    listEmailConfigs(productId: bigint): Promise<Array<EmailConfigView>>;
    listEmailLogs(productId: bigint): Promise<Array<EmailLog>>;
    listEmailTemplates(productId: bigint): Promise<Array<EmailTemplateView>>;
    listIssueComments(issueId: bigint): Promise<Array<IssueComment>>;
    listIssues(productId: bigint | null, status: IssueStatus | null, severity: IssueSeverity | null): Promise<Array<IssueView>>;
    listLinkedApps(): Promise<Array<LinkedAppView>>;
    listNotifications(notifType: NotificationType | null, productId: bigint | null, isRead: boolean | null): Promise<Array<NotificationView>>;
    listProductUpdates(productId: bigint): Promise<Array<UpdateView>>;
    listProducts(): Promise<Array<ProductView>>;
    listUserActivities(productId: bigint): Promise<Array<UserActivity>>;
    listUsers(): Promise<Array<UserView>>;
    listUsersByProduct(productId: bigint): Promise<Array<UserView>>;
    logUserActivity(userId: bigint, productId: bigint, eventType: ActivityEventType, description: string): Promise<void>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(id: bigint): Promise<void>;
    markUpdateDeployed(id: bigint): Promise<void>;
    reconnectProduct(id: bigint): Promise<void>;
    registerLinkedApp(name: string, baseUrl: string, appCode: string): Promise<LinkedAppView>;
    registerProduct(name: string, description: string, code: string): Promise<ProductView>;
    removeLinkedApp(id: string): Promise<boolean>;
    removeUser(id: bigint): Promise<void>;
    resolveAlert(id: bigint): Promise<void>;
    resolveIssue(id: bigint): Promise<void>;
    restoreUser(id: bigint): Promise<void>;
    scheduleUpdate(id: bigint, scheduledAt: Time): Promise<void>;
    snoozeNotification(id: bigint, until: Time): Promise<void>;
    submitMetrics(productId: bigint, cpu: bigint, memory: bigint, disk: bigint, apiLatency: bigint, networkUptime: bigint, connectionStatus: string): Promise<SystemMetrics>;
    suspendUser(id: bigint): Promise<void>;
    syncProduct(id: bigint): Promise<void>;
    updateEmailConfig(id: bigint, senderName: string, senderEmail: string, bounceEmail: string, isActive: boolean): Promise<void>;
    updateEmailTemplate(id: bigint, subject: string, body: string): Promise<void>;
    updateIssue(id: bigint, title: string, description: string, severity: IssueSeverity, status: IssueStatus, assignedTo: bigint | null): Promise<void>;
    updateLinkedAppStatus(id: string, status: string): Promise<LinkedAppView | null>;
    updateProductMeta(id: bigint, name: string, description: string): Promise<void>;
    updateUserRole(id: bigint, role: UserRole): Promise<void>;
}
import type { ActivityEventType as _ActivityEventType, AlertView as _AlertView, EmailLog as _EmailLog, EmailStatus as _EmailStatus, Id as _Id, IssueId as _IssueId, IssueSeverity as _IssueSeverity, IssueStatus as _IssueStatus, IssueView as _IssueView, LinkedAppView as _LinkedAppView, MetricSeverity as _MetricSeverity, NotificationSeverity as _NotificationSeverity, NotificationType as _NotificationType, NotificationView as _NotificationView, ProductId as _ProductId, ProductStatus as _ProductStatus, ProductView as _ProductView, SystemMetrics as _SystemMetrics, Timestamp as _Timestamp, UpdateId as _UpdateId, UpdateStatus as _UpdateStatus, UpdateView as _UpdateView, UserActivity as _UserActivity, UserId as _UserId, UserRole as _UserRole, UserStatus as _UserStatus, UserView as _UserView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addEmailLog(arg0: bigint, arg1: string, arg2: string, arg3: EmailStatus): Promise<EmailLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmailLog(arg0, arg1, arg2, to_candid_EmailStatus_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_EmailLog_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmailLog(arg0, arg1, arg2, to_candid_EmailStatus_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_EmailLog_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addIssueComment(arg0: bigint, arg1: string, arg2: bigint): Promise<IssueComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addIssueComment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIssueComment(arg0, arg1, arg2);
            return result;
        }
    }
    async createAlert(arg0: bigint, arg1: string, arg2: MetricSeverity, arg3: bigint, arg4: bigint): Promise<AlertView> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, arg1, to_candid_MetricSeverity_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return from_candid_AlertView_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, arg1, to_candid_MetricSeverity_n7(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return from_candid_AlertView_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEmailConfig(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<EmailConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmailConfig(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmailConfig(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createEmailTemplate(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<EmailTemplateView> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmailTemplate(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmailTemplate(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createIssue(arg0: string, arg1: string, arg2: IssueSeverity, arg3: bigint, arg4: bigint | null): Promise<IssueView> {
        if (this.processError) {
            try {
                const result = await this.actor.createIssue(arg0, arg1, to_candid_IssueSeverity_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return from_candid_IssueView_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIssue(arg0, arg1, to_candid_IssueSeverity_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return from_candid_IssueView_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: NotificationSeverity, arg3: NotificationType, arg4: bigint | null): Promise<NotificationView> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, to_candid_NotificationSeverity_n24(this._uploadFile, this._downloadFile, arg2), to_candid_NotificationType_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return from_candid_NotificationView_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, to_candid_NotificationSeverity_n24(this._uploadFile, this._downloadFile, arg2), to_candid_NotificationType_n25(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return from_candid_NotificationView_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUpdate(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<UpdateView> {
        if (this.processError) {
            try {
                const result = await this.actor.createUpdate(arg0, arg1, arg2, arg3);
                return from_candid_UpdateView_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUpdate(arg0, arg1, arg2, arg3);
            return from_candid_UpdateView_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: bigint, arg1: string, arg2: string, arg3: UserRole): Promise<UserView> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg3));
                return from_candid_UserView_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg3));
            return from_candid_UserView_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEmailConfig(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmailConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmailConfig(arg0);
            return result;
        }
    }
    async deleteEmailTemplate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmailTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmailTemplate(arg0);
            return result;
        }
    }
    async disconnectProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disconnectProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disconnectProduct(arg0);
            return result;
        }
    }
    async dismissNotification(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNotification(arg0);
            return result;
        }
    }
    async getLatestMetrics(arg0: bigint): Promise<SystemMetrics | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestMetrics(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestMetrics(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetricsHistory(arg0: bigint): Promise<Array<SystemMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetricsHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetricsHistory(arg0);
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<ProductView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveAlerts(): Promise<Array<AlertView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveAlerts();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveAlerts();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAlertHistory(arg0: bigint): Promise<Array<AlertView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlertHistory(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlertHistory(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUpdates(): Promise<Array<UpdateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUpdates();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUpdates();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmailConfigs(arg0: bigint): Promise<Array<EmailConfigView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmailConfigs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmailConfigs(arg0);
            return result;
        }
    }
    async listEmailLogs(arg0: bigint): Promise<Array<EmailLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmailLogs(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmailLogs(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmailTemplates(arg0: bigint): Promise<Array<EmailTemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmailTemplates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmailTemplates(arg0);
            return result;
        }
    }
    async listIssueComments(arg0: bigint): Promise<Array<IssueComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIssueComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIssueComments(arg0);
            return result;
        }
    }
    async listIssues(arg0: bigint | null, arg1: IssueStatus | null, arg2: IssueSeverity | null): Promise<Array<IssueView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIssues(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIssues(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n56(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLinkedApps(): Promise<Array<LinkedAppView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLinkedApps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLinkedApps();
            return result;
        }
    }
    async listNotifications(arg0: NotificationType | null, arg1: bigint | null, arg2: boolean | null): Promise<Array<NotificationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications(to_candid_opt_n58(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n59(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications(to_candid_opt_n58(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n59(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductUpdates(arg0: bigint): Promise<Array<UpdateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductUpdates(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductUpdates(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<ProductView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUserActivities(arg0: bigint): Promise<Array<UserActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserActivities(arg0);
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserActivities(arg0);
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByProduct(arg0: bigint): Promise<Array<UserView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByProduct(arg0);
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByProduct(arg0);
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async logUserActivity(arg0: bigint, arg1: bigint, arg2: ActivityEventType, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logUserActivity(arg0, arg1, to_candid_ActivityEventType_n68(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logUserActivity(arg0, arg1, to_candid_ActivityEventType_n68(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markUpdateDeployed(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markUpdateDeployed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markUpdateDeployed(arg0);
            return result;
        }
    }
    async reconnectProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reconnectProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reconnectProduct(arg0);
            return result;
        }
    }
    async registerLinkedApp(arg0: string, arg1: string, arg2: string): Promise<LinkedAppView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLinkedApp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLinkedApp(arg0, arg1, arg2);
            return result;
        }
    }
    async registerProduct(arg0: string, arg1: string, arg2: string): Promise<ProductView> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProduct(arg0, arg1, arg2);
                return from_candid_ProductView_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProduct(arg0, arg1, arg2);
            return from_candid_ProductView_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeLinkedApp(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLinkedApp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLinkedApp(arg0);
            return result;
        }
    }
    async removeUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async resolveAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0);
            return result;
        }
    }
    async resolveIssue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveIssue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveIssue(arg0);
            return result;
        }
    }
    async restoreUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.restoreUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restoreUser(arg0);
            return result;
        }
    }
    async scheduleUpdate(arg0: bigint, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleUpdate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleUpdate(arg0, arg1);
            return result;
        }
    }
    async snoozeNotification(arg0: bigint, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.snoozeNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.snoozeNotification(arg0, arg1);
            return result;
        }
    }
    async submitMetrics(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string): Promise<SystemMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMetrics(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async suspendUser(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async syncProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.syncProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.syncProduct(arg0);
            return result;
        }
    }
    async updateEmailConfig(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmailConfig(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmailConfig(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateEmailTemplate(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmailTemplate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmailTemplate(arg0, arg1, arg2);
            return result;
        }
    }
    async updateIssue(arg0: bigint, arg1: string, arg2: string, arg3: IssueSeverity, arg4: IssueStatus, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIssue(arg0, arg1, arg2, to_candid_IssueSeverity_n14(this._uploadFile, this._downloadFile, arg3), to_candid_IssueStatus_n54(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIssue(arg0, arg1, arg2, to_candid_IssueSeverity_n14(this._uploadFile, this._downloadFile, arg3), to_candid_IssueStatus_n54(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateLinkedAppStatus(arg0: string, arg1: string): Promise<LinkedAppView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLinkedAppStatus(arg0, arg1);
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLinkedAppStatus(arg0, arg1);
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProductMeta(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductMeta(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductMeta(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUserRole(arg0: bigint, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityEventType_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEventType): ActivityEventType {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_AlertView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertView): AlertView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_EmailLog_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailLog): EmailLog {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_EmailStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailStatus): EmailStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_IssueSeverity_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueSeverity): IssueSeverity {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_IssueStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueStatus): IssueStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_IssueView_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueView): IssueView {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MetricSeverity_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetricSeverity): MetricSeverity {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationSeverity_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationSeverity): NotificationSeverity {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationView_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationView): NotificationView {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ProductView_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductView): ProductView {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateStatus): UpdateStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateView): UpdateView {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserActivity_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserActivity): UserActivity {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserView_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserView): UserView {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemMetrics]): SystemMetrics | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductView]): ProductView | null {
    return value.length === 0 ? null : from_candid_ProductView_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LinkedAppView]): LinkedAppView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    resolved: boolean;
    value: bigint;
    threshold: bigint;
    productId: bigint;
    timestamp: _Timestamp;
    severity: _MetricSeverity;
    metricType: string;
    resolvedAt: [] | [_Timestamp];
}): {
    id: Id;
    resolved: boolean;
    value: bigint;
    threshold: bigint;
    productId: bigint;
    timestamp: Timestamp;
    severity: MetricSeverity;
    metricType: string;
    resolvedAt?: Timestamp;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        value: value.value,
        threshold: value.threshold,
        productId: value.productId,
        timestamp: value.timestamp,
        severity: from_candid_MetricSeverity_n11(_uploadFile, _downloadFile, value.severity),
        metricType: value.metricType,
        resolvedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.resolvedAt))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IssueId;
    status: _IssueStatus;
    title: string;
    assignedTo: [] | [bigint];
    createdAt: _Timestamp;
    description: string;
    productId: bigint;
    updatedAt: _Timestamp;
    severity: _IssueSeverity;
}): {
    id: IssueId;
    status: IssueStatus;
    title: string;
    assignedTo?: bigint;
    createdAt: Timestamp;
    description: string;
    productId: bigint;
    updatedAt: Timestamp;
    severity: IssueSeverity;
} {
    return {
        id: value.id,
        status: from_candid_IssueStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assignedTo)),
        createdAt: value.createdAt,
        description: value.description,
        productId: value.productId,
        updatedAt: value.updatedAt,
        severity: from_candid_IssueSeverity_n22(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    title: string;
    notifType: _NotificationType;
    body: string;
    createdAt: _Timestamp;
    productId: [] | [bigint];
    isRead: boolean;
    snoozedUntil: [] | [_Timestamp];
    severity: _NotificationSeverity;
    snoozed: boolean;
}): {
    id: Id;
    title: string;
    notifType: NotificationType;
    body: string;
    createdAt: Timestamp;
    productId?: bigint;
    isRead: boolean;
    snoozedUntil?: Timestamp;
    severity: NotificationSeverity;
    snoozed: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotificationType_n29(_uploadFile, _downloadFile, value.notifType),
        body: value.body,
        createdAt: value.createdAt,
        productId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.productId)),
        isRead: value.isRead,
        snoozedUntil: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.snoozedUntil)),
        severity: from_candid_NotificationSeverity_n31(_uploadFile, _downloadFile, value.severity),
        snoozed: value.snoozed
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UpdateId;
    status: _UpdateStatus;
    deployedAt: [] | [_Timestamp];
    createdAt: _Timestamp;
    size: bigint;
    productId: bigint;
    releaseNotes: string;
    version: string;
    scheduledAt: [] | [_Timestamp];
}): {
    id: UpdateId;
    status: UpdateStatus;
    deployedAt?: Timestamp;
    createdAt: Timestamp;
    size: bigint;
    productId: bigint;
    releaseNotes: string;
    version: string;
    scheduledAt?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_UpdateStatus_n34(_uploadFile, _downloadFile, value.status),
        deployedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.deployedAt)),
        createdAt: value.createdAt,
        size: value.size,
        productId: value.productId,
        releaseNotes: value.releaseNotes,
        version: value.version,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.scheduledAt))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    lastActivity: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    productId: bigint;
    email: string;
}): {
    id: UserId;
    status: UserStatus;
    lastActivity: Timestamp;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    productId: bigint;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n40(_uploadFile, _downloadFile, value.status),
        lastActivity: value.lastActivity,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n42(_uploadFile, _downloadFile, value.role),
        productId: value.productId,
        email: value.email
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _EmailStatus;
    subject: string;
    recipient: string;
    productId: bigint;
    timestamp: _Timestamp;
}): {
    id: Id;
    status: EmailStatus;
    subject: string;
    recipient: string;
    productId: bigint;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_EmailStatus_n5(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        recipient: value.recipient,
        productId: value.productId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    status: _ProductStatus;
    code: string;
    name: string;
    description: string;
    registeredAt: _Timestamp;
    lastSync: _Timestamp;
}): {
    id: ProductId;
    status: ProductStatus;
    code: string;
    name: string;
    description: string;
    registeredAt: Timestamp;
    lastSync: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n48(_uploadFile, _downloadFile, value.status),
        code: value.code,
        name: value.name,
        description: value.description,
        registeredAt: value.registeredAt,
        lastSync: value.lastSync
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    userId: _UserId;
    description: string;
    productId: bigint;
    timestamp: _Timestamp;
    eventType: _ActivityEventType;
}): {
    id: Id;
    userId: UserId;
    description: string;
    productId: bigint;
    timestamp: Timestamp;
    eventType: ActivityEventType;
} {
    return {
        id: value.id,
        userId: value.userId,
        description: value.description,
        productId: value.productId,
        timestamp: value.timestamp,
        eventType: from_candid_ActivityEventType_n65(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
}): NotificationSeverity {
    return "warning" in value ? NotificationSeverity.warning : "info" in value ? NotificationSeverity.info : "critical" in value ? NotificationSeverity.critical : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    in_progress: null;
} | {
    open: null;
}): IssueStatus {
    return "resolved" in value ? IssueStatus.resolved : "in_progress" in value ? IssueStatus.in_progress : "open" in value ? IssueStatus.open : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): IssueSeverity {
    return "low" in value ? IssueSeverity.low : "high" in value ? IssueSeverity.high : "critical" in value ? IssueSeverity.critical : "medium" in value ? IssueSeverity.medium : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    systemAlert: null;
} | {
    user: null;
} | {
    update: null;
} | {
    issue: null;
}): NotificationType {
    return "systemAlert" in value ? NotificationType.systemAlert : "user" in value ? NotificationType.user : "update" in value ? NotificationType.update : "issue" in value ? NotificationType.issue : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deployed: null;
} | {
    scheduled: null;
} | {
    pending: null;
} | {
    failed: null;
}): UpdateStatus {
    return "deployed" in value ? UpdateStatus.deployed : "scheduled" in value ? UpdateStatus.scheduled : "pending" in value ? UpdateStatus.pending : "failed" in value ? UpdateStatus.failed : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    viewer: null;
}): UserRole {
    return "manager" in value ? UserRole.manager : "admin" in value ? UserRole.admin : "viewer" in value ? UserRole.viewer : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    disconnected: null;
} | {
    connected: null;
}): ProductStatus {
    return "disconnected" in value ? ProductStatus.disconnected : "connected" in value ? ProductStatus.connected : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sent: null;
} | {
    failed: null;
} | {
    bounced: null;
}): EmailStatus {
    return "sent" in value ? EmailStatus.sent : "failed" in value ? EmailStatus.failed : "bounced" in value ? EmailStatus.bounced : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: null;
} | {
    login: null;
} | {
    permissionChange: null;
}): ActivityEventType {
    return "action" in value ? ActivityEventType.action : "login" in value ? ActivityEventType.login : "permissionChange" in value ? ActivityEventType.permissionChange : value;
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertView>): Array<AlertView> {
    return value.map((x)=>from_candid_AlertView_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UpdateView>): Array<UpdateView> {
    return value.map((x)=>from_candid_UpdateView_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailLog>): Array<EmailLog> {
    return value.map((x)=>from_candid_EmailLog_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IssueView>): Array<IssueView> {
    return value.map((x)=>from_candid_IssueView_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationView>): Array<NotificationView> {
    return value.map((x)=>from_candid_NotificationView_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductView>): Array<ProductView> {
    return value.map((x)=>from_candid_ProductView_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserActivity>): Array<UserActivity> {
    return value.map((x)=>from_candid_UserActivity_n63(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserView>): Array<UserView> {
    return value.map((x)=>from_candid_UserView_n38(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityEventType_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): _ActivityEventType {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_EmailStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): _EmailStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_IssueSeverity_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueSeverity): _IssueSeverity {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_IssueStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueStatus): _IssueStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_MetricSeverity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetricSeverity): _MetricSeverity {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationSeverity_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationSeverity): _NotificationSeverity {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueStatus | null): [] | [_IssueStatus] {
    return value === null ? candid_none() : candid_some(to_candid_IssueStatus_n54(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueSeverity | null): [] | [_IssueSeverity] {
    return value === null ? candid_none() : candid_some(to_candid_IssueSeverity_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType | null): [] | [_NotificationType] {
    return value === null ? candid_none() : candid_some(to_candid_NotificationType_n25(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueSeverity): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == IssueSeverity.low ? {
        low: null
    } : value == IssueSeverity.high ? {
        high: null
    } : value == IssueSeverity.critical ? {
        critical: null
    } : value == IssueSeverity.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmailStatus): {
    sent: null;
} | {
    failed: null;
} | {
    bounced: null;
} {
    return value == EmailStatus.sent ? {
        sent: null
    } : value == EmailStatus.failed ? {
        failed: null
    } : value == EmailStatus.bounced ? {
        bounced: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    systemAlert: null;
} | {
    user: null;
} | {
    update: null;
} | {
    issue: null;
} {
    return value == NotificationType.systemAlert ? {
        systemAlert: null
    } : value == NotificationType.user ? {
        user: null
    } : value == NotificationType.update ? {
        update: null
    } : value == NotificationType.issue ? {
        issue: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    admin: null;
} | {
    viewer: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.admin ? {
        admin: null
    } : value == UserRole.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueStatus): {
    resolved: null;
} | {
    in_progress: null;
} | {
    open: null;
} {
    return value == IssueStatus.resolved ? {
        resolved: null
    } : value == IssueStatus.in_progress ? {
        in_progress: null
    } : value == IssueStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): {
    action: null;
} | {
    login: null;
} | {
    permissionChange: null;
} {
    return value == ActivityEventType.action ? {
        action: null
    } : value == ActivityEventType.login ? {
        login: null
    } : value == ActivityEventType.permissionChange ? {
        permissionChange: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationSeverity): {
    warning: null;
} | {
    info: null;
} | {
    critical: null;
} {
    return value == NotificationSeverity.warning ? {
        warning: null
    } : value == NotificationSeverity.info ? {
        info: null
    } : value == NotificationSeverity.critical ? {
        critical: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
